#LOCAL
spring.profiles.active=local

# DATABASE
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# APP
spring.application.name=project-bsr

# JACKSON
spring.jackson.default-property-inclusion=non-null

# JWT
jwt.secret=
app.security.jwt.expiration-ms=
app.security.jwt.refresh-expiration-ms=

# CORS
app.security.cors.allowed-origins=http://localhost:4200


# FILE UPLOAD
upload.root=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# MAIL
spring.mail.host=
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# FRONTEND
app.frontend.url=http://localhost:4200

# STRIPE
app.stripe.secret-key=
app.stripe.webhook-secret=